FROM python:3.7-slim-buster
RUN apt-get update \
         && apt-get -y install libpq-dev gcc \
         && pip install "FLASK==1.1.1" flask-sqlalchemy psycopg2 flask-migrate flask-script marshmallow flask-bcrypt pyjwt
WORKDIR .
COPY . .
EXPOSE 5000:5000
ENTRYPOINT ["python"]
CMD ["run.py"]
